Added extensions of the pH-meter SEN0161
letssteam/pxt-lets-steam pull request #140
Opened 2023-11-08 14:33 UTC by Charly-sketch

2023-11-08 14:45 UTC, jnthbdn requested changes

2023-11-08 14:45 UTC, jnthbdn commented on libs/anemometer/pxt.json
> +  "description": "An anemometer measuring rotation per minute / frequency of anemometer's cup rotation /test",
Visiblement un petit message de debug est resté ici ^^

2023-11-08 14:45 UTC, jnthbdn commented on libs/phmeter/sim/visual.ts
> +      let w = PHMETER_HUM_PART_WIDTH;
Il reste des `_HUM` dans certains noms de variables

2023-11-08 14:45 UTC, jnthbdn commented on libs/phmeter/sim/visual.ts
> +
Pour chipoter tu peux retirer les sauts de lignes inutiles ^^

2023-11-09 06:39 UTC, nedseb approved these changes

2023-11-10 14:55 UTC, jnthbdn approved these changes

2023-11-10 14:57 UTC, merged